# Generated by Django 5.1.3 on 2024-12-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('SP', 'Store Pickup'), ('EH', 'Express Home Delivery'), ('RH', 'Regular Home Delivery')], max_length=2)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
