# Generated by Django 5.1.3 on 2024-12-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_cost',
        ),
    ]
