# Generated by Django 5.1.3 on 2024-12-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('user_credential_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.inventoryitems')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_credential_details.usercredentialdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
