# Generated by Django 5.1.3 on 2024-12-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping_bag', '0001_initial'),
        ('user_credential_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shopping_bag', to='user_credential_details.usercredentialdetails'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingbag',
            unique_together={('user', 'inventory')},
        ),
    ]
