# Generated by Django 5.1.3 on 2024-12-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-3'),
            preserve_default=False,
        ),
    ]
