# Generated by Django 5.1.3 on 2024-12-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0003_alter_shoppingbag_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingbag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shoppingbag',
            name='user',
        ),
    ]
