# Generated by Django 5.1.3 on 2024-12-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('shopping_bag', '0005_remove_shoppingbag_created_at_and_more'),
        ('user_credential_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingbag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingbag',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingbag',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shoppingbag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_credential_details.usercredentialdetails'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='shoppingbag',
            unique_together={('user', 'inventory')},
        ),
    ]
