# Generated by Django 5.1.3 on 2024-12-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('SP', 'Store Pickup'), ('EH', 'Express Home Delivery'), ('RH', 'Regular Home Delivery')], max_length=2)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('due_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
