# Generated by Django 5.1.3 on 2024-12-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('order', '0001_initial'),
        ('user_credential_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('user', 'inventory')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
