# Generated by Django 5.1.3 on 2024-12-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
