# Generated by Django 5.1.3 on 2024-12-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_payment_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentdetails',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='userpaymentdetails',
            name='expiry_month',
            field=models.CharField(choices=[('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12')], default='02', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpaymentdetails',
            name='expiry_year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035')], default='2025', max_length=4),
            preserve_default=False,
        ),
    ]
