# Generated by Django 5.1.3 on 2024-12-03 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0002_usershippingdetails_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershippingdetails',
            options={'verbose_name_plural': 'Inventories'},
        ),
    ]
