# Generated by Django 5.1.3 on 2024-12-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_shipping_details', '0003_alter_usershippingdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usershippingdetails',
            options={'verbose_name_plural': 'User Shipping Details'},
        ),
    ]
